### 2-3

In [1]:
import numpy as np
stochastic_mat=np.array([[0.8,0.2,0],[0.4,0.4,0.2],[0.2,0.6,0.2]])
stochastic_mat

array([[0.8, 0.2, 0. ],
       [0.4, 0.4, 0.2],
       [0.2, 0.6, 0.2]])

In [2]:
measure_mat=np.array([[0.6,0.4,0],[0.3,0.7,0],[0,0,1]])
measure_mat

array([[0.6, 0.4, 0. ],
       [0.3, 0.7, 0. ],
       [0. , 0. , 1. ]])

In [5]:
measured_list=['c','c','r','s']
wether_map=dict(s=0,c=1,r=2)

In [25]:
bel=[]
bel.append( np.array( [1,0,0]) )

In [15]:
bel_bar=[]
bel_bar_tdy=[]
bel_bar_tdy.append(stochastic_mat[bel[0][0],0])
bel_bar_tdy.append(stochastic_mat[bel[0][1],])

In [26]:
stochastic_mat[0,0]*bel[0][0]

0.8

In [29]:
bel_bar_tdy=bel[0] @ stochastic_mat
bel_bar_tdy

array([0.8, 0.2, 0. ])

In [44]:
#実際は晴れで、計測が曇りのときの確率(の定数倍)
measure_mat[0,1]*bel_bar_tdy[0]

0.32000000000000006

In [43]:
bel_tdy=measure_mat[:,1]*bel_bar_tdy
bel_tdy=bel_tdy/bel_tdy.sum()
bel_tdy

array([0.69565217, 0.30434783, 0.        ])

In [21]:
bel[0][1]

0

In [62]:
wether=measured_list[0]
#計測が曇りのときの実際の天気の確率
bel_tdy=measure_mat[:,wether_map[wether]]*bel_bar_tdy
bel_tdy/=bel_tdy.sum()
bel_tdy

array([0.69565217, 0.30434783, 0.        ])

In [6]:
wether_bel=np.array([1,0,0])
for measuerd in measured_list:
    #前の天気の確率に確率行列をかけて、計測する前の天気の確率とする。
    bel_bar=wether_bel @ stochastic_mat
    #計測がmeasuerdのときのそれぞれの実際の天気の確率
    wether_bel=measure_mat[:,wether_map[measuerd]]*bel_bar
    wether_bel/=wether_bel.sum()
    print(wether_bel)

[0.69565217 0.30434783 0.        ]
[0.59770115 0.40229885 0.        ]
[0. 0. 1.]
[0.4 0.6 0. ]


### (b)

In [9]:
measured_list=['s','s','r']
wether_bel=np.array([1,0,0])
for measuerd in measured_list:
    #前の天気の確率に確率行列をかけて、計測する前の天気の確率とする。
    bel_bar=wether_bel @ stochastic_mat
    #計測がmeasuerdのときのそれぞれの実際の天気の確率
    wether_bel=measure_mat[:,wether_map[measuerd]]*bel_bar
    wether_bel/=wether_bel.sum()
    print(wether_bel)

[0.88888889 0.11111111 0.        ]
[0.87179487 0.12820513 0.        ]
[0. 0. 1.]


$$
p(x_1|z_1)=0.88\\
p(x_1|z_{1:2})=\eta p(z_2|x_1z_1)p(x_1|z_1)
$$

$$
p(z_2|x_1,z_1)=\int p(z_2|x_2)p(x_2|x_1)dx_2
$$

$$
p(x_1=s)=1
$$